#-------------------------------
# General Site Settings
title: c4rta
logo: # You can add own logo. For example '/images/logo.png'.
description: Average nerd who loves cybersecurity
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://ic4rta.github.io" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: c4rta
  avatar: 'https://secure.gravatar.com/avatar/713f0634508cc8fd29f98ff6d84d86af?s=150'


#-------------------------------
# Hero Settings
hero:
  title: c4rta
  description: Average nerd who loves cybersecurity
  image: 'assets/img/fondo6.jpg'


#-------------------------------
# Contact Settings
contact:
  email:  # Add your email for contact form
  description: no se que poner. # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/_c4rta_"}
- {icon: "ion-logo-github", link: "https://github.com/ic4rta"}


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: n00b2h4ck3r # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
#google-analytics: UA-176116253-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
#mailchimp-identifier: https://app.us20.list-manage.com/subscribe/post?u65e25d0a60609c8cbde82c607;id=4eaddf4109 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
