email: fanxiaobin422@gamil.com
author: c4rta
title: c4rta
description: >- #这意味着在“baseurl:”之前忽略换行符
  Hacking e informatica
baseurl: "" # 您网站的子路径，例如 /blog
url: "https://ic4rta.github.io/" # 您站点的基本主机名和协议，例如 e.g. http://example.com
favicon: "/favicon.png" # 您网站的图标
permalink: date

# 版权设置
# * 您可以使用任何 html 代码，目前以下占位符可用：
# * 当前年份：{currentYear}
# * 作者: {author}（值与site.author相同）
# * 版权：(c) - ©
# * 公共版权: (cleft)
# * 录音版权：(p) - ℗
#例如：
#    "Copyright (c) 2017-{currentYear} <a href=https://example.com>{author}</a>"
#    “版权所有 © 2017-2021 Foobar”

copyright: "Copyright (c) 2017-{currentYear} <a href=https://github.com/ic4rta/>{author}</a>"

yat:
  date_format: "%b %d, %Y"

# Build settings
markdown: kramdown
#highlighter: rouge
kramdown:
  input: GFM
  #syntax_highlighter: rouge
  
# Disqus 评论
#disqus:
# shortname: "vanhiupun"

# 摘录大小设置
excerpt_size: 150

# 如果要生成网站站点地图，可以设置为true
sitemap: true

# 分页设置
paginate: 10

# 如果您只想链接标题中的特定页面，请取消注释
# 按顺序添加页面的路径
header_pages:
  - index.html
  - categories.html
  - tags.html
  - about.md

# Google Analytics
google_analytics: "UA-212989441-1"    # 你用Google账号去注册一个就会给你一个这样的id
enableDNT: true

#如果要改变内容宽度，可以设置为其他值
content_width: "1080px"

# 文章图标设置
# 您可以启用或禁用文章图标等
code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#ff4e00"
  text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# admin 页面 
# jekyll_admin:
#   hidden_links:
#     - posts
#     - pages
#     - staticfiles
#     - datafiles
#     - configuration
#   homepage: "pages"

# Gitment 评论
#gitment:
#  username: "" # github用户名
#  repo: "" # 仓库名称
#  client_id: "" # Client ID
#  client_secret: "" # Client secrets
#  redirect_uri: "" # 如果你使用自定义域名

# Translate languges
translate_langs: []

#如果你想改变网站语言，你可以设置 lang 选项
#lang: "en" # 默认语言为 en

#可以选择主题颜色
#默认主题颜色如下：
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
theme_color: snowwhite
#
# 自定义颜色如下:
# theme_color: "#882250"

#您可以选择品牌颜色
#默认品牌颜色如下：
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
# brand_color: orangered
#
#自定义颜色如下：
# brand_color： "＃1a8e42"

#如果你想要更多的调试日志，你可以设置为true
debug: true

#如果你不想要透明的header，你可以设置false
header_transparent: true

theme: jekyll-text-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-admin
  - jemoji
  - webrick
